spring:
  datasource:
    username: username
    url: jdbc:h2:./tmp/devDb;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090
    driverClassName: org.h2.Driver
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
