DROP TABLE IF EXISTS student;
CREATE TABLE student(
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR (128) NOT NULL
);

DROP TABLE IF EXISTS course;
CREATE TABLE course(
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR (128) NOT NULL
);

DROP TABLE IF EXISTS registration CASCADE;
CREATE TABLE registration
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    course_id  INTEGER NOT NULL,
    CONSTRAINT fk_student_id FOREIGN KEY (student_id) REFERENCES student (id),
    CONSTRAINT fk_course_id FOREIGN KEY (course_id) REFERENCES course (id)
);